 const data ={
    "titleList": [
      "Fullmetal Alchemist",
      "Death Note ",
      "Cowboy Bebop",
      "Spirited Away ",
      "Princess Mononoke",
      "(The) Melancholy of Haruhi Suzumiya ",
      "Elfen Lied",
      "Neon Genesis Evangelion",
      "Code Geass: Lelouch of the Rebellion",
      "Bleach ",
      "Code Geass: Lelouch of the Rebellion R ",
      "FLCL ",
      "Naruto ",
      "Samurai Champloo ",
      "Trigun ",
      "Gurren Lagann ",
      "Rurouni Kenshin: Trust & Betrayal (OAV)",
      "Howl's Moving Castle ",
      "Full Metal Panic! ",
      "Ouran High School Host Club ",
      "Fullmetal Alchemist: Brotherhood ",
      "Clannad ",
      "Fruits Basket ",
      "Akira ",
      "Cowboy Bebop: The Movie",
      "Chobits ",
      "Full Metal Panic? Fumoffu ",
      " Centimeters Per Second ",
      "Rurouni Kenshin (TV )",
      "(The) Girl Who Leapt Through Time ",
      "Ghost in the Shell ",
      "Clannad After Story ",
      "Hellsing ",
      "Final Fantasy VII: Advent Children ",
      "Azumanga Daioh ",
      "Fullmetal Alchemist: The Movie - Conqueror of Shamballa",
      "Ghost in the Shell: Stand Alone Complex ",
      "Nausicaä of the Valley of the Wind ",
      "Mushi-Shi ",
      "Darker than Black ",
      "Fate/stay night ",
      "Steins;Gate ",
      "Claymore ",
      "Toradora! ",
      "Inuyasha ",
      "Full Metal Panic! The Second Raid ",
      "Castle in the Sky ",
      "Black Lagoon ",
      "Blood+ ",
      "Angel Beats! ",
      "Neon Genesis Evangelion: The End of Evangelion ",
      "My Neighbor Totoro ",
      "Grave of the Fireflies ",
      "Dragon Ball Z ",
      "Eureka Seven ",
      "Air ",
      "Love Hina ",
      "Berserk ",
      "Last Exile ",
      "When They Cry - Higurashi ",
      "GTO: Great Teacher Onizuka ",
      "Baccano! ",
      "Wolf's Rain ",
      "Welcome to the NHK ",
      "Sword Art Online ",
      "Serial Experiments Lain ",
      "Shakugan no Shana ",
      "Haibane Renmei ",
      "One Piece ",
      "Attack on Titan ",
      "Kiki's Delivery Service ",
      "Naruto Shippūden ",
      "(The) Vision of Escaflowne ",
      "Samurai  ",
      "Soul Eater ",
      "Ergo Proxy ",
      "School Rumble ",
      "Black Lagoon: The Second Barrage ",
      "Spice and Wolf ",
      "Lucky Star ",
      "Eden of the East ",
      "Kanon (TV /)",
      "Gungrave ",
      "Dragon Ball ",
      "Puella Magi Madoka Magica ",
      "Monster ",
      "High School of the Dead ",
      "Summer Wars ",
      "Chrono Crusade ",
      "Bakemonogatari ",
      "anohana: The Flower We Saw That Day ",
      "Gunslinger Girl ",
      "Lunar Legend Tsukihime ",
      "(The) Familiar of Zero ",
      "ROD -The TV-",
      "Read orDie (OAV)",
      "Yu Yu Hakusho: Ghost Files",
      "Mobile Suit Gundam Seed",
      "Durarara!!",
      "Paranoia Agent "
    ]
  }

  export default data;